### ISSUE TITLE
PhewasMeta producing error

### ISSUE THREAD

**Issue by amymariemason** [PheWAS/PheWAS#12]
I get the error 
**"Error in bind_rows_(x, .id) : 
  Argument 1 must be a data frame or a named atomic vector, not a by"** 
 when attempting to run phewasMeta.

I'm running through RStudio, on R 3.4.2 on a Windows 7 Professional machine. 

I'm running the code from the example in phewasMeta:

#Generate some example data
ex=generateExample(hit="335")
#Extract the two parts from the returned list
id.icd9.count=ex$id.icd9.count
genotypes=ex$genotypes
#Create the PheWAS code table- translates the icd9s, adds exclusions, and reshapes to a wide format
phenotypes=createPhewasTable(id.icd9.count)
#Run the PheWAS
results.1=phewas(phenotypes,genotypes,cores=4,significance.threshold=c("bonferroni"))
#Set up a study identifier
results.1$study="335"
#Perform another PheWAS
ex=generateExample(hit="250.2")
id.icd9.count=ex$id.icd9.count
genotypes=ex$genotypes
phenotypes=createPhewasTable(id.icd9.count)
results.2=phewas(phenotypes,genotypes,cores=4,significance.threshold=c("bonferroni"))
results.2$study="250.2"
#Join the two sets of PheWAS results
results=rbind(results.1,results.2)
#Perform the meta analysis, and do not assume fixed effects.
results.meta=phewasMeta(results, fixed=FALSE, keep.both=FALSE)

Please advise?

**Comment by RobertJCarroll** [comment]
Thanks for the note. Unfortunately, `dplyr::bind_rows` was changed to no longer support "by" objects. I updated the code to use `group_by` and `do`. Please let me know if you have any issues moving forward.
