### ISSUE TITLE
Can I use ICD-10 codes instead of ICD9?

### ISSUE THREAD

**Issue by SulevR** [PheWAS/PheWAS#14]
Can I use ICD-10 codes instead of ICD9 or is there some sort of reason for limit? It seems that if use ICD-10 codes in "icd9" column, everything works well, except plotting:

```
library(PheWAS)
set.seed(1)
ex=generateExample(n=1000,phenotypes.per=10,hit="4")
#replace by some random ICD-10 diagnoses
ex$id.icd9.count$icd9<-paste('I',sample(1:25,replace=T, nrow(ex$id.icd9.count)),sep="")

#Extract the two parts from the returned list
id.icd9.count=ex$id.icd9.count
genotypes=ex$genotypes
#Create the phecode table- translates the icd9s, adds 
#exclusions, and reshapes to a wide format
phenotypes=createPhewasTable(id.icd9.count,
                             min.code.count = 1,
                             add.exclusions = F,
                             translate = F,
                             aggregate.fun = sum)
#Run the PheWAS
results=phewas(phenotypes,genotypes,cores=1,
               significance.threshold=c("bonferroni"))
#Plot the results
phewasManhattan(results, annotate.angle=0,
                title="My Example PheWAS Manhattan Plot")

```

Result:

```
Error in phenotypePlot(d, suggestive.line = suggestive.line, significant.line = significant.line,  : 
  Annotate.phenotype.description must contain columns phenotype and description, or be TRUE with provided d$description.
In addition: Warning messages:
1: In phewasManhattan(results, annotate.angle = 0, title = "My Example PheWAS Manhattan Plot") :
  Phenotypes with length <3 observed, ensure they are are 0-padded (e.g., "008")
2: In max(d$value) : no non-missing arguments to max; returning -Inf
```

In addition, it seems that dash ("-") is not allowed in diagnosis codes (eg. J10-J18, a valid ICD-10 range).

However, the question is whether I can use the package for ICD-10 diagnoses in general (except for plotting) or is there some sort of reason for limiting the usage for ICD-9 only.

**Comment by RobertJCarroll** [comment]
Hi there. I believe there are really a few questions all bundled together; I'll try and answer as best I can.
1. The package does not support converting ICD10 or ICD10CM codes to phecodes (yet). That work is in progress.
2. One may use whatever phenotypes/predictors one would like. You have used the correct modes (translate=F and exclude=F) for createPhewasTable (which is essentially just a tall->wide translation at this point).
3. In order to use custom codes (ie, not phecodes) in plotting, one must use the phenotypeManhattan() function.

I'm working on a restructure of the code so some of these issues are more immediately clear. Please let me know if this doesn't address your problems.

**Comment by SulevR** [comment]
Thanks! And what is the benefit of using phecodes instead of "whatever phenotypes"? Is it only the grouping of ICD-9 diagnoses?

**Comment by RobertJCarroll** [comment]
Phecodes were originally created as hierarchical groupings of ICD9CM billing codes. They are structured to be more focused on "clinically meaningful phenotypes" as opposed to billing artifacts, and help address the way information can be disjointed in the single hierarchy of ICD9CM. Over time, they have been refined in the context of discovery research. There are advantages and disadvantages to each; it depends on one's end goal. One can certainly use ICD10 codes (or ranges/groups of codes) as an input phenotypes!
[Here is a manuscript that describes an evaluation comparing phecodes, CCS groupings, and raw ICD9CM codes for EHR PheWAS](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5501393/)

**Comment by SulevR** [comment]
Thank you, Robert! All questions answered. However, I think this thread is a useful input for other researchers also using this package.
