### ISSUE TITLE
phenotypeManhattan() error

### ISSUE THREAD

**Issue by katya-dun** [PheWAS/PheWAS#18]
Hello, I am hoping to get some clarification on why the phenotypeManhattan() function is giving me errors. I am using my own phenotypes (not ICD-9 codes) for the purpose of my study. 

<img width="757" alt="screen shot 2018-10-24 at 2 24 01 pm" src="https://user-images.githubusercontent.com/39524530/47452601-a7803c00-d798-11e8-838c-f8349b5370fb.png">

**Comment by RobertJCarroll** [comment]
Regarding the error, one of the following should work:
1. Set "use.color=F" if you do not wish to color your points.
2. Put color values for each point in results$color. This is what phewasManhattan() does using addPhecodeInfo().
3. Use a factor in results$color and have a list of color values in color.palette.

I'll note you are likely to also encounter a similar error regarding groups. The same goes there: add a results$group variable (or set x.group.labels=F). Adding results$groupnum is needed for sorting by group (which is done for phewasManhattan()).

**Comment by katya-dun** [comment]
This worked, thank you!

**Comment by RobertJCarroll** [comment]
I'm glad that worked. Best wishes for your research!
