### ISSUE TITLE
A question about PheCode rollup

### ISSUE THREAD

**Issue by huangming6220** [PheWAS/PheWAS#22]
I am interested in using PheCode developed by your group. But I am not clear about the meaning of PheCode rollup. Take the following PheCodes for example, 

PheCode | Rollup
276       | 1
276.1    | 1
276.11  | 1
276.4    | 0
276.41  | 1

My understanding and confusion is:

276.11 can be grouped into 276.1 (Rollup=1) and 276.1 can be grouped into 276 (Rollup=1). Why does 276 still have a rollup value of 1? What code can 276 roll up to?
In contrast, 276.41 can be grouped into 276.4 (Rollup=1), but 276.4 can NOT be grouped into 276 (Rollup=0). So 276.4 and 276 are both root code, are they?
 
Thank you very much!

**Comment by RobertJCarroll** [comment]
I believe that rollup of 1 is the default, so 3-digit codes have that by default. There are only a handful of codes that do not roll up and may be considered parent codes as you indicate. I believe the package only uses the unrolled version which integrates the "rollup" part.
