### ISSUE TITLE
Dosage support

### ISSUE THREAD

**Issue by erkinacar5** [PheWAS/PheWAS#23]
Hello,

Does the current PheWAS package support dosage input (instead of 0,1,2 genotypes)? If not, are you planning to include this in the future?

Currently, when I give dosage information as genotype input, I get separate results for all the dosages that are different than 0, 1, or 2.

Thanks,
Erkin

**Comment by RobertJCarroll** [comment]
Hi there. One can input anything as predictors. The column(s) simply gets handed on to R's glm (or similar) function. The 0,1,2 is only regarding the HWE calculations. I have used phewas() for dosage and polygenic risk scores with no issues.

I can't see your results, but it sounds like your input into the genotype field is represented in R as a factor and not a numeric type. That would yield result rows for each observed value.  If one is using a representation of allele counts probabilities, eg 0:0.5:0.5 for AA:Aa:aa, one would need to convert that to a single dosage estimate, eg 1.5.

**Comment by erkinacar5** [comment]
Indeed it was my own mistake, sorry for troubling :)
