### ISSUE TITLE
Question: why doesn't phewasManhattan work with small datasets?

### ISSUE THREAD

**Issue by PhilPalmer** [PheWAS/PheWAS#28]
Hi,

I am doing a phewas analysis and trying to produce a Manhattan plot (see [RScript](https://github.com/PhilPalmer/phewas/blob/master/bin/phewas.R))

I have been testing it with datasets of different sizes. 

I am always able to run the phewas fine, however, when I try plotting the results with:
```R
phewasManhattan(results, annotate.angle=0)
```

I often receive this error:
```
  Error in phenotypePlot(d, suggestive.line = suggestive.line, significant.line = significant.line,  :
    Annotate.phenotype.description must contain columns phenotype and description, or be TRUE with provided d$description.
  Calls: phewasManhattan -> phenotypeManhattan -> phenotypePlot
  In addition: Warning message:
  In max(d$value) : no non-missing arguments to max; returning -Inf
```

I have looked at the `results` data frame that is used for the plot I think it fails because all of the `p`-values are `NA`. As if I change these values the plot works. Any idea what causes the p-values to be `NA`? Eg is it because for each SNP there must be information at that position for at least two individuals?

Any help would be much appreciated

Many thanks in advance,
Phil

**Comment by RobertJCarroll** [comment]
Hi Phil. If you check the `note` field in the results object, it likely documents why the test would not have been run. It could be a lack of cases or controls as you mention.

**Comment by PhilPalmer** [comment]
Thanks, @RobertJCarroll for your prompt response

Yes, I think the problem is the lack of cases & controls as the `note` field has:
```
Error: < 20 complete records
```

Do you know what exactly is required to perform a test? Eg for any given phenotype & SNP combination do you need at least 20 individuals either in the case or control group?

**Comment by RobertJCarroll** [comment]
From the documentation: `min.records The minimum number of records to perform a test. For logistic regression, there must be at least this number of each cases and controls, for linear regression this total number of records. Default is 20.`
You can check ?PheWAS::phewas_ext or https://github.com/PheWAS/PheWAS/blob/master/man/phewas_ext.Rd for more details.
