### ISSUE TITLE
firth logistic regression for phewas

### ISSUE THREAD

**Issue by Annefeng** [PheWAS/PheWAS#29]
Hi,

For my research project I'd like to use Firth's logistic regression to run a phewas. I saw that a firth logistic regression script is created (phe_as_logsitf.R) and wonder if it has been fully tested and if yes, what is the best practice to using it? Thanks for the help!

**Comment by RobertJCarroll** [comment]
phewas_ext(...,method='logistf') will use that inner function you mentioned to perform Firth regression using the logistf package (so we are relying on their implementation to be robust). I believe the inner function is up to date on our end. You should be able to use it just like a logistic regression PheWAS, though it may be slower given the increased computational needs.
