### ISSUE TITLE
 In n * p : NAs produced by integer overflow

### ISSUE THREAD

**Issue by wym0072003** [PheWAS/PheWAS#30]
Hi,

I got an issue in run createPhewasTable. Can you please give me favor?

> phenotypes=createPhewasTable(csv.phenotypes,min.code.count=1,translate = F,add.exclusions = F)
Aggregating codes...
Coalescing exclusions and min.code.count as applicable...
Reshaping data...
Error in if (m < n * p && (m == 0L || (n * p)%%m)) stop(sprintf(ngettext(m,  :
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: Please see PheWAS::createPhenotypes() for more features. This function will be removed in the future.
2: In n * p : NAs produced by integer overflow
3: In n * p : NAs produced by integer overflow

Best,

Yiming

**Comment by RobertJCarroll** [comment]
The error is coming from another function call within createPhewasTable external to PheWAS. You'd need to run the call in debug mode and catch where exactly the error is happening.

Based on the logging output, my suspicion is that your data is too large and it's breaking in the spread() call.

**Comment by wym0072003** [comment]
Yes, it could be. I tested on only one variant, but the sample size is up to 400K. Is there any way to deal with this? The computer is OK, which has a 128 Gb RAM. Thanks!

**Comment by RobertJCarroll** [comment]
The variants don't matter yet in this case.

Keep in mind that I made an (arguably informed) guess about your problem. If you want to solve it, you'll need to do what I recommended above: run the command again with debug mode on, and identify what nested function call is breaking and why (eg what n and p are that n * p is causing an integer overflow). Anything I suggest will be a conjecture until you can identify the root of the problem.

If I am correct in my supposition above, however, breaking up the 'csv.phenotypes' into chunks by ID and merging the result could work around the issue. EG, try to split the 'csv.phenotypes' into sets of 100k IDs. It's likely not a RAM problem (ie, the dataset is too big to store) it's a single integer overflow problem.

I'll also note that it appears you are not using most of the real benefits of this method, eg translation to phecodes and exclusion criteria and minimum code count. At that point, it may be simpler (and easier to debug) to just do the reshaping/spread operation yourself depending on what your input is.
