### ISSUE TITLE
Filtering in createPhenotypes

### ISSUE THREAD

**Issue by cperriard** [PheWAS/PheWAS#31]
Hi, 

it seems that the filtering in the function `createPhenotypes` at the end does not have any effect since the results of the filtering are not assigned to a variable: 
https://github.com/PheWAS/PheWAS/blob/888b063f6abe2015415ffd7cd39f11923c5123a0/R/createPhenotypes.R#L75

In addition this filtering operation may take a lot of resources and even create out of memory errors with a lot of individuals. 
And since the filtering is done after the spread it could be that some codes that only occure in individuals that are later filtered out. In such case the codes would get zeros for all remaining individuals. Is this behavior intended? Or should the filtering be moved up? 

Thanks!

**Comment by RobertJCarroll** [comment]
Thanks for this comment, it is a mistake there.

The workflow of the `full.population.ids` is to support adding "control rows" or ensuring all of those who don't have any relevant phecodes in the input are still captured. Users would be better served providing input for only those individuals they are interested in seeing phecodes for, so I don't expect this will really change much. I could actually drop the statement I expect as well- not sure why the check is there!
