### ISSUE TITLE
How to generate the index column for id.vocab.code.index in createPhenotypes

### ISSUE THREAD

**Issue by Diwadkar** [PheWAS/PheWAS#33]
The input data frame ( id.vocab.code.index) for the function createPhenotypes() consists of four columns: id, vocabulary_id, code, and index. What does the index column mean exactly?

**Comment by RobertJCarroll** [comment]
It's a flexible column. By default it supports dates (which get counted uniquely for the phecode) and numbers (which are summed). You can define your own aggregation function as well with `aggregate.fun`.

**Comment by Diwadkar** [comment]
Thank you!
