### ISSUE TITLE
Very high odds ratio

### ISSUE THREAD

**Issue by wym0072003** [PheWAS/PheWAS#34]
Hi,

I got some very high odds ratio after running phewas with default setting. Some OR can reach to 300-400. My sample size is up to 30k. 

May I ask for some possible reason caused this? 
Thanks.

Best,

Yiming

**Comment by RobertJCarroll** [comment]
Hi there. Without any information about the data beyond sample size, it's not possible for me to help more. I would recommend checking the note field to see if the model perhaps didn't converge. I would also run the association tests with glm() to get more information. phewas_ext() reports the formula used, so it's easy to plug that into your own model.

**Comment by wym0072003** [comment]
Thanks Robert, I found it may due to the model didn't converge because of extremely unbalanced cases and controls. I have repeated some tests with glm() using logistic regression, but got similar results.
How to check the formula using phewas_ext()? Didn't see formula with viewing the function.
Thanks again.

Best,

Yiming

**Comment by RobertJCarroll** [comment]
Glad you have identified what is happening.

One of the columns that is returned is called "formula" and is the r-style formula that was provided to glm(). The "expanded_formula" column is what the model "actually looks like" after expansion, eg dummy coding of variables.
