### ISSUE TITLE
the result of phenotype translate into ICD-code

### ISSUE THREAD

**Issue by fengxmyxb** [PheWAS/PheWAS#35]
Hi:
I'd appreciate it if you could answer my question
I am doing an analysis of Phewas using ICD10-code, I have two columns in the result, one column is description,another is phenotype. I found phecode_map_ICD10 in the website of Github,what I want to konw is whether the phecode is the phenotype?Because I want to macth the decription of positive result in the phewasManhattan plot with ICD10-code.
Another problem is significance.threshold, I choose the bonferroni method,but it is too strict,I want to use the fdr method,but I found the result and Manhattan plot are same using two different methods.
The following is my R-code:
results=phewas(phenotypes,genotypes,covariates=covariates,cores=4,significance.threshold=c("bonferroni"))
phewasManhattan(results, annotate.angle=0)
#the colums of phenotypes is using ICD10 code

**Comment by fengxmyxb** [comment]
and the example of id.vocab.code.count,what the concrete meaning of count？Number of occurrences of a phenotype?

**Comment by RobertJCarroll** [comment]
Hi there-
I'm not completely following your use of the tools in the package, and you only describe a couple of calls, so I can't get a full picture. It may help to familiarize yourself some with the documentation in the package and the examples, eg here: https://github.com/PheWAS/PheWASExamples/tree/master/BMI_FTO 

If you are translating to phecodes using `createPhenotypes(...,translate=T)` (the default), the `phenotype` column of `phewas_ext()` will contain the phecode. I presume you are doing this given you are discussing the `description` column of `addPhecodeInfo`. To identify the specific ICD10 codes that are built into each phecode, you could look here for an interface: https://phewascatalog.org/phecodes_icd10 

Note that the maps provided in the package are mostly not "unrolled", ie they are only the direct mappings of ICD9CM/10/10CM codes to phecodes, and do not include all of the parent phecodes.

Re the "significance threshold", that method returns an additional column; it will not affect the plot. There is also a `significant.line` for the `phewasManhattan` function you can use if you are interested in adjusting the line. Additionally, you can apply the FDR approach and plot the q values as there is not an "FDR line" in the same way there is for a bonferroni correction.

Regarding the `id.vocab.code.index` parameter, one can use counts of occurrences or dates. The decision of what to use depends on one's specific use case, objectives, and attributes of the underlying data and reporting system.

**Comment by fengxmyxb** [comment]
Thank you for your answer
I don't quite understand what you mean about **_id.vocab.code.count_**,for example,I have some data(
100 | D259 | F171 | H251| N840 | N950 | Z016 | 
101 | R410 | R55 |   
102 | D24 | K112 | K579 | M199 | N731|  )
how can I konw the count?
I try to define the count as some number,such as 100 1~6   101  1~2  102   1~5
is it right?
