### ISSUE TITLE
id.vocab.code.count,what the meaning of count?

### ISSUE THREAD

**Issue by fengxmyxb** [PheWAS/PheWAS#36]
Thank you for your answer
I don't quite understand what you mean about "count",for example,I have some data(
100 | D259 | F171 | H251| N840 | N950 | Z016 |
101 | R410 | R55 |  
102 | D24 | K112 | K579 | M199 | N731|  )
how can I konw the count?
I try to define the count as some number,if one person have 6 illness,I try to define the count as1~6,
is it right?
id     icd     count   
100 D259 1
100  F171 2
100 H251 3
100  N840 4
100 N950 5
100 Z016  6

**Comment by fengxmyxb** [comment]
I've seen other writers raise this issue as well,
such as  **Diwadkar opened this issue on 22 Apr · 2 comments**,and the reply is **aggregate fun**,
I use the "??aggregate fun" in R,but it show nothing. Only I could found it in creatPhewasTable, but I could not understand its meaning.

**Comment by fengxmyxb** [comment]
Thank you very much for your answer. I feel I could understand your meaning. First of all, the data I exported from EHR is how many diseases a patient has.For example,
If the same patient was hospitalized 5 times for hypertension, and the hypertension was derived from the inpatient record system, then the hypertension was shown 5 times,  count is 5
But the data we collected, this patient showed hypertension only once, did not repeat the ICD code for hypertension, count is 1?

**Comment by fengxmyxb** [comment]
Thank you very much for your answer. I feel I could understand your meaning about count. First of all, the data I exported from EHR is how many diseases a patient has.
For example,
If one patient was hospitalized 5 times for hypertension, and the diagnostic information of hypertension was derived from the inpatient record system, then the ICD10 code of hypertension was shown 5 times in the data file,  so the count is 5.
If this data file was cleaned up,  the ICD10 code of hypertension of this patient was shown only once, did not show the repeated ICD10 code for hypertension, then the count should be 1？

**Comment by RobertJCarroll** [comment]
That sounds reasonable, though I'd be sure to set `min.code.count=1` in the second scenario as you no longer have longitudinal information.
Ideally, one would have dates so that codes that are different ICD10 codes but the same phecode do not count twice on the same day.
Having said that- changing `min.code.count` has the same sensitivity/specificity tradeoffs one would expect from changing a threshold in machine learning / information retrieval tasks. You can always set it to 1 to be very sensitive, or increase it to be more specific if you need to (though of course that's assuming what's generally observed re codes holds to the specific case you are interested in).

**Comment by fengxmyxb** [comment]
Your answer clears up my confusion for a long time. Thank you very much for your help！

**Comment by fengxmyxb** [comment]
Hello again.
I have another question about ICD9 and ICD10 codes,If a person has both an ICD9-diagnosed disease and an ICD10-diagnosed disease,for example
id vab icd count
1001 ICD9 71.4 1
1001 ICD9 65.2 1
1002 ICD10 A04.9 1
1002 ICD9   42.5 1
1002 ICD10 B02 1
1002 ICD10 B03 1
How could I use the function of **createPhenotypes**？I found ICD9 codes using createPhewasTable,but if one person have two ICD codes,what should I do?

**Comment by keoughkath** [comment]
Hello,

I have an issue that seems related to the above. I'm working with binary phenotypes, so I've inputted them as shown above where for each individual, there's an ICD10 code if the patient has the condition, then a "1". I used min.code.count=1, however when I try to use createPhenotypes on this dataframe I get the below error. Any idea how I can fix this? Thanks!

```
> phenotypes=createPhenotypes(icd10cm_codes,
+                             min.code.count=1,
+                             id.sex=id_sex,
+                             add.phecode.exclusions=F)
Mapping codes to phecodes...
Aggregating codes...
Coalescing exclusions and min.code.count as applicable...
Reshaping data...
Error in UseMethod("filter") : 
  no applicable method for 'filter' applied to an object of class "c('integer', 'numeric')"
In addition: Warning messages:
1: In max(!is.na(phecode$count) & phecode$count < min.code.count) :
  no non-missing arguments to max; returning -Inf
2: In max(count) : no non-missing arguments to max; returning -Inf
```
