### ISSUE TITLE
object 'formula.string' not found

### ISSUE THREAD

**Issue by r-mustafa** [PheWAS/PheWAS#39]
Hi,

I run phewas_ext() with script below which worked in my local PC (R version 3.6.3, PheWAS_0.99.5-4), but didn't worked on a cluster (R version 4.0.0, PheWAS_0.12).

> res=phewas_ext(dat,phenotypes=col$pheno7,genotypes=c(SNP),
+                    covariates=covar.list)
Finding associations...
Error in data.frame(phenotype = phe, snp = gens, covariates = covariates,  :
  object 'formula.string' not found

I am not sure what is causing the error since all the input datasets are the same. I used anaconda to install PheWAS in the cluster so I am not sure if this problem appears due to different version of R/PheWAs being used. I'd ppreciate if you could let me know what tou think.

Many thanks,
Rima

**Comment by RobertJCarroll** [comment]
Hello. I'd definitely look to update the package, as `0.12` is several years old. I've never used anaconda to install packages, so I'm not sure what is going on there.
