### ISSUE TITLE
some questions regarding the package

### ISSUE THREAD

**Issue by hik010** [PheWAS/PheWAS#40]
Hi.
I had some questions regarding the PheWAS package. 
1) Just to double check, this PheWAS package take ICD10 or ICD9 codes for input right? Is it possible to perform it on quantitative phenotypes instead? 
2) Is it possible to run associations with our own groupings of the phenotypes? For example, we wanted the 3 groups: immune related phenotypes, cancer phenotypes, everything else. If we can categorize the phecodes into our own categories, can we run association with our categories?
3) Is it possible to make the p-values multiple hypothesis tested? or request for some statistical significance thresholds such as FDR when running phewas_ext()?

Thanks.

**Comment by RobertJCarroll** [comment]
Apologies for the delay on response.

1. Regarding the input options, yes, ICD9CM and ICD10CM are supported. `createPhenotypes` has details for the conversion. Regarding quantitative phenotypes, numeric outcomes are analyzed by linear regression, which may meet your needs.
2. Yes, you can combine the phenotypes any way you see fit. One can provide an alternate mapping in `createPhenotypes` with the various map parameters, eg by adding to the `rollup.map`. It may be easier to do it after the translation and combine the columns.
3. This is probably easiest to apply post-hoc as well by transforming the p-value output. For example, apply `p.adjust` to the p-value column.
