### ISSUE TITLE
PheWAS plot issue

### ISSUE THREAD

**Issue by xuj18** [PheWAS/PheWAS#42]
Hi Robert,
   Thanks for creating the PheWAS package! I wanted to create a PheWAS plot with the top finding in each disease category annotated. I tried annotating this through the annotate.list function. Below is the code I used (I used ICD-10 codes rather than phecodes in my data):

pheno_list <-c("F32.9","E66.01") #the ICD-10 codes that I want to annotate
phenotypeManhattan(files[[4]], max.y=25, annotate.size=4,  annotate.list=pheno_list,annotate.phenotype=TRUE,suggestive.line=NA, significant.line=0.0000019, size.x.labels=20,size.y.labels=20, switch.axis=F,point.size=3, title=" ", x.group.labels=F, x.axis.label=" ")

However, this PheWAS plot still gave me all the annotations above the significant line instead of the annotation of the 2 ICD-10 codes. Do you know how I should code to get what I want? Thanks so much!

Best,
Jiayi

**Comment by RobertJCarroll** [comment]
By default, `phenotypeManhattan` annotates all points below the significance threshold, see:

> annotate.level	
> For phenotypeManhattan, annotate points at or below this p with a default of genomewide.line For phenotypePlot, minimum value to annotate points. Default of no annotation.

Setting `annotate.level=0` should meet your use case. I can look at tweaking this a little to make it more robust and clear.

**Comment by RobertJCarroll** [comment]
Ok, the latest commit includes the option and documentation for `annotate.level=NA` to explicitly turn this off.

**Comment by xuj18** [comment]
Thank you Robert! I will give it a try!
