### ISSUE TITLE
Installing PheWAS using devtools::install_github("PheWAS/PheWAS")

### ISSUE THREAD

**Issue by Ikayanjoh** [PheWAS/PheWAS#44]
May I kindly ask your assistance, I've try to installing PheWAS in R but i have no luck
I keep getting this error. please see below

Installing package into ‘C:/Program Files/R/R-4.0.3/library’
(as ‘lib’ is unspecified)
* installing *source* package 'PheWAS' ...
** using staged installation
Error in as.POSIXlt.POSIXct(x, tz) : 
  (converted from warning) unknown timezone 'GMT'
ERROR: installing package DESCRIPTION failed for package 'PheWAS'
* removing 'C:/Program Files/R/R-4.0.3/library/PheWAS'
Error: Failed to install 'PheWAS' from GitHub:
  (converted from warning) installation of package ‘C:/Users/JDELPI~2/AppData/Local/Temp/RtmpSQFOCr/file3334263e76b8/PheWAS_0.99.5-5.tar.gz’ had non-zero exit status

**Comment by RobertJCarroll** [comment]
From doing a little searching, this sounds like it may be an issue with your local environment configuration. Perhaps the solution offered here would help: https://stackoverflow.com/questions/59286203/r-error-installing-source-packages-unknown-timezone-gmt
