### ISSUE TITLE
what is id.vocab.code.count

### ISSUE THREAD

**Issue by tianbu** [PheWAS/PheWAS#47]
Hi,

I am preparing the input files for the package. However, in the example, there is a count called id.vocab.code.count. What does id.vocab.code.count mean? And how to calculate that? Thanks!

**Comment by RobertJCarroll** [comment]
There is an example here: https://github.com/PheWAS/PheWASExamples/tree/master/BMI_FTO 
The icd_codes.csv file specifically.

The help file also describes this field:
`id.vocab.code.index`	

> Data frame with four columns of information: id, vocabulary_id, code, and index. The id and index columns can have other names, but id must be consistent among input files. The vocabulary_id and code must match up with the vocabulary.map file. The default supports the vocabularies "ICD9CM" and "ICD10CM".

The approach to generating it is dependent on your data source and use case. EG, in OMOP it's the person_id, vocabulary_id, concept_code, <and whatever you'd like to use as an index, eg, date or total count>.

**Comment by tianbu** [comment]
Thanks! I have read the description previously. But It is still confusing though. Let's say, it is an index.  What kind of index is it? index for ICD code? Index for sampleID+ICD code? Then look at the below lines from the example you mentioned:

id,vocabulary_id,code,count
7076,ICD10CM,A49.9,67200,ICD10CM,A49.9,6
3083,ICD10CM,A49.9,2
5048,ICD10CM,A49.9,3Why the index (count) are different for some of the samples which have identical ICD10CM code?

If this is count data, then does it mean how many samples in the database have the same ICD10M condition? If so, then the counts should be identical. That's why I can't understand that. And does id.vocab.code.index affect the results? My understanding is phewas working on SNP in all phenotypes in the provided database. 
And the number of cases and controls (assume this is a binary dataset) who carries the SNP will affect the beta and SE.  So I think it is important to understand what kind of index or count data it is. 
Thank you very much!

**Comment by RobertJCarroll** [comment]
The `id` is an individual's ID- none of the rows are re the population.

Regarding the content of the `index`, that's a scientific question that needs to be answered in the context of the study design. Same with the minimum code count (`min.code.count`) and the aggregation approach (`aggregate.fun`). The original PheWAS approach looked at distinct code-days, but that requires aggregating across ICD codes (as a phecode may have many ICD codes) and then doing the distinct count of dates. The simpler method from database is to aggregate on `id, vocabulary_id, code` and get the distinct date count, then feed that into this method (which joins and reshapes).
