### ISSUE TITLE
Error: non-varying phenotype or genotype

### ISSUE THREAD

**Issue by ali22stark** [PheWAS/PheWAS#52]
Hello,

I have been trying to run a PheWAS for one of my projects, and I have been getting a few errors that I don't understand (I am a biologist by training, and also a new scientist).

First, in the id.vocab.code.count (or id.vocab.code.index) file, what information is supposed to go in the count/index column? I haven't been able to find any information on this.

Second, when i use the createPhenotypes function, the resulting phenotypes file only contains FALSE and NA values (no TRUE), even when a sample does report that code in the id.vocab.code.index file. How do I create a phenotypes file that also correctly contains the TRUE values?

Finally, when I run the actual PheWAS, the statistics fields of the results file are empty and the "note" column shows "Error: non-varying phenotype or genotype".

What do these errors mean? I have been trying to get this to run for over a month and can't seem to figure it out. 

Thank you!!

**Comment by RobertJCarroll** [comment]
Hi there. 

That parameter is either a count of occurrences of the code or a date of the event. The example here uses a count: https://github.com/PheWAS/PheWASExamples/blob/master/BMI_FTO/icd_codes.csv . PheWAS uses a minimum code count as a threshold to adjust specificity, ie the more codes an individual has the more likely they are to have the condition but the fewer individuals that will meet the criteria. What you put in this field is specific to your data and analysis plan. The original PheWAS approach is to include, for each individual and code combination, a row with each date that individual had that code. Then, if two source codes (eg, ICD9CM and ICD10CM) codes indicate the same phecode on a single day they will not be double counted.

Re 2: It sounds like you are not using an appropriate count or index, so it will not work.

Re 3: You describe a file that has no cases, so

**Comment by ali22stark** [comment]
Thank you!

I looked at the example file and am a little confused about how to calculate the "count" variable. Is the count the number of total occurrences of that specific code across all samples, or the number of occurrences reported for a single sample?

**Comment by RobertJCarroll** [comment]
The `id` field specifies the individual, and the `count` in that row is for that individual and code. If a person has three different ICD9CM and ICD10CM codes, they should have three rows in the input dataset.

This input with dates would work:
id, vocabulary_id, code, index
1, ICD9CM, 250.02, 2021-01-01
1, ICD9CM, 250.02, 2021-01-02
1, ICD9CM, 250.02, 2021-01-03
1, ICD9CM, 410.0, 2021-01-01
1, ICD9CM, 008.0, 2021-01-03
2, ICD9CM, 250.02, 2021-06-01

Or you can summarize it to counts:
1, ICD9CM, 250.02, 3
1, ICD9CM, 410.0, 1
1, ICD9CM, 008.0, 1
2, ICD9CM, 250.02, 1

The first option is "best" from the output perspective as the package will translate to phecodes first, then do the "unique dates with this phecode", while it's possible the second might double-count some codes on the same day.

**Comment by ali22stark** [comment]
Adding in the counts fixed things. Thank you for all of your help!
