### ISSUE TITLE
High resource usage and long runtime on large computers

### ISSUE THREAD

**Issue by pettyalex** [PheWAS/PheWAS#55]
Hello,

My group has seen the PheWAS package use all available system resources and take a very long time to complete, even on smaller datasets. I'm fairly certain that this is happening because the default  BLAS implementation when setting up R through Conda with `r-base`  is trying to use all available system threads to do some work that does not multi-thread effectively. 

We observed the same behavior with [the SAIGE R package](https://github.com/weizhouUMICH/SAIGE), and were able to correct it by specifically setting R's BLAS usage to use only 1 thread.

We can do this either by setting an environment variable when running PheWAS `OMP_NUM_THREADS=1` for OpenBLAS or `MKL_NUM_THREADS=1` for the Intel MKL, or by using a tool like [an R package to control thread usage](https://cran.r-project.org/web/packages/RhpcBLASctl/index.html).

What R environment was this developed in? Should this package be using multiple threads? I'm going to make a PR to set thread usage to 1 so that it should run better with default settings in more environments. 

I'm still testing PheWAS on some test data to compare how much of a difference this could make, but making the change to SAIGE made it run hundreds of times faster for us. I'm expecting a similar improvement with PheWAS.

Our R environment `sessionInfo()`
```
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

Matrix products: default
BLAS/LAPACK: /belowshare/vumcshare/data100t1/home/alex/.conda/envs/alex/envs/r4/lib/libopenblasp-r0.3.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.2
```

A computer doing nothing other than running 1 instance of PheWAS package with cores=1
![image](https://user-images.githubusercontent.com/3219141/157551506-b91e4c45-83ed-4d32-8415-6123a6e170f2.png)

**Comment by pettyalex** [comment]
I finished doing some basic benchmarking on a test dataset, and with the `OMP_NUM_THREADS` environment variable set to `1`, it took:
```
User time (seconds): 1610.26
System time (seconds): 13.14
``` 

In default configuration without that variable set:
```
User time (seconds): 30778.49
System time (seconds): 134571.48
```

That is, 46 hours vs 27 minutes

**Comment by RobertJCarroll** [comment]
With default parameters, I'm not aware of anything that would cause it to use multiple threads. Using `phewas_ext(..., cores=2)` would use `parallel` to do parallel processing. I'm not aware of anyone who has used it in this kind of setting- mostly standard R sessions across linux / macos / windows. It is possible there's some other kind of optimization that's been done that doesn't play nicely with with the approach + standard methods.

**Comment by pettyalex** [comment]
The root cause of this was that the BLAS library that our R is linked against was trying to use 1 thread per core, even when the underlying operations were not suited to it. We saw the same issue on SAIGE [as documented here, and in other linked issues](https://github.com/weizhouUMICH/SAIGE/issues/380).

We resolved this by setting the environment variable `OMP_NUM_THREADS=1` before running PheWAS, which restricts each process to 1 single thread, even for linear algebra information.

Here's are some resources about linking R to other BLAS implementations, and why it's done. In our case, it was the default configuration when installing R through conda:
* https://brettklamer.com/diversions/statistical/faster-blas-in-r/
* https://www.r-bloggers.com/2013/07/for-faster-r-use-openblas-instead-better-than-atlas-trivial-to-switch-to-on-ubuntu/
* https://csantill.github.io/RPerformanceWBLAS/
* https://mpopov.com/blog/2019/06/04/faster-matrix-math-in-r-on-macos/
* https://thomasmcrow.com/blog/2021-08-optimized-blas-in-r/
