### ISSUE TITLE
Trouble using function

### ISSUE THREAD

**Issue by RobertJCarroll** [PheWAS/PheWAS#57]
Hello,

I have an issue that seems related to the above. I'm working with binary phenotypes, so I've inputted them as shown above where for each individual, there's an ICD10 code if the patient has the condition, then a "1". I used min.code.count=1, however when I try to use createPhenotypes on this dataframe I get the below error. Any idea how I can fix this? Thanks!

```
> phenotypes=createPhenotypes(icd10cm_codes,
+                             min.code.count=1,
+                             id.sex=id_sex,
+                             add.phecode.exclusions=F)
Mapping codes to phecodes...
Aggregating codes...
Coalescing exclusions and min.code.count as applicable...
Reshaping data...
Error in UseMethod("filter") : 
  no applicable method for 'filter' applied to an object of class "c('integer', 'numeric')"
In addition: Warning messages:
1: In max(!is.na(phecode$count) & phecode$count < min.code.count) :
  no non-missing arguments to max; returning -Inf
2: In max(count) : no non-missing arguments to max; returning -Inf
```

_Originally posted by @keoughkath in https://github.com/PheWAS/PheWAS/issues/36#issuecomment-1196218455_

**Comment by keoughkath** [comment]
From working on this a bit more, it seemed to be either my column names or their order, but either way it's working now so I'll close this. Thanks!

**Comment by RobertJCarroll** [comment]
Ok great!
