### ISSUE TITLE
issue with createPhewasTable 

### ISSUE THREAD

**Issue by rcorty** [PheWAS/PheWAS#59]
I'm using the following lines of code...

```
phecodes_raw <- read_delim('genotyped_phecode_2019-10-22.txt', delim='|')
glimpse(phecodes_raw)
```
which gives
```
Rows: 5,654,162
Columns: 5
$ GRID     <chr> "XXX", "YYY", "ZZZ", "AAA", "BBB…
$ PHECODE  <chr> "871.2", "351", "401.1", "483", "949", "1010", "745", "721.1", "43…
$ FIRST_DX <dttm> 2012-05-30, 2006-09-19, 2009-05-28, 2005-04-26, 2016-08-25, 2007-…
$ LAST_DX  <dttm> 2012-05-30 00:00:00, 2006-09-19 00:00:00, 2009-06-13 00:00:00, 20…
$ COUNTS   <dbl> 1, 1, 2, 1, 5, 8, 8, 2, 1, 7, 4, 86, 7, 9, 5, 1, 13, 2, 2, 1, 7, 1…
```
Then I run
```
phecodes_for_phewastable <- phecodes_raw %>% select(id = GRID, phe = PHECODE, count=COUNTS)
phenotypes <- createPhewasTable(id.icd9.count = phecodes_for_phewastable, translate = FALSE)
```
I noticed that if I don't name the first two arguments 'id' and 'phe', I get a quick error advising me to do that.
I noticed that if I don't name the third argument 'count', I get an error after it's been running a while.

However, with this set up I am getting 
```
Error in `setdiff()`:
! `y` must be a data frame.
```

And the backtrace gives...
```
---
Backtrace:
 1. PheWAS::createPhewasTable(...)
 3. dplyr:::setdiff.data.frame(ids, phens[["id"]])
Run `rlang::last_trace()` to see the full context.
```

I'm wondering if I've inputted the data incorrectly or if there might be some error internally?

**Comment by RobertJCarroll** [comment]
This function is deprecated, so I would not use it. You should be getting a warning telling you to use `createPhenotypes()` instead (which you should do). If you aren't getting that warning, I would recommend updating the package as well.

I'm not 100% sure re this bug, but I believe it's an issue with the way `tibble`s handle indexing differently than `data.frame`s. The outdated code expects a dataframe and doesn't handle this gracefully. The approach is different in the newer function, so it should resolve your issue. Alternatively, you can turn your `tibble` into a `data.frame` and it may work.

**Comment by rcorty** [comment]
Thank you. I'm on the current version of PheWAS and getting a warning that says:

```
Please see PheWAS::createPhenotypes() for more features. This function will be removed in the future.
```

In any case, I will switch to `createPhenotypes()`.

Somewhat related - package vignette currently uses `createPhewasTable`.

**Comment by RobertJCarroll** [comment]
Sounds good- please let me know if you see similar problems after you switch.
