### ISSUE TITLE
Issue when applying createPhenotypes function

### ISSUE THREAD

**Issue by TheKursta** [PheWAS/PheWAS#62]
Dear Authors,

I'm trying to apply the `createPhenotypes` function, however, I get an error `object of type 'closure' is not subsettable`.
I'm using R version 3.6.3.
Input:
```
library(PheWAS)
diabetes_data=data.frame(id=1:5,
                         vocabulary_id=c("ICD10CM","ICD10CM","ICD10CM","ICD10CM","ICD10CM"),
                         code=c("A09","A56.0","A63.8","A69.2","A63.8"), 
                         count = c(1,1,1,1,1))

diabetes_phecodes = createPhenotypes(data, 
                                     min.code.count=1, 
                                     vocabulary.map=PheWAS::phecode_map_icd10)

```

Thrown error:
```
Error in id.vocab.code.index[[3]] : 
  object of type 'closure' is not subsettable
```

All the best,
Klavs

**Comment by RobertJCarroll** [comment]
You are applying `createPhenotypes()` to the R function named `data`, not to your `diabetes_data` data frame.

Additionally- you have specified your vocabulary as ICD10CM, but you are also trying to use the ICD10 code map. If you are actually supplying ICD10CM codes (eg, you are using data from the US), then you don't need to specify a `vocabulary.map`. If you are using ICD10 codes (eg, you are using data from the UK), then please make sure your input data reflects that.

**Comment by TheKursta** [comment]
Thank you for your quick and detailed answer!
