### ISSUE TITLE
Content of "count" variable in the input

### ISSUE THREAD

**Issue by curranth** [PheWAS/PheWAS#63]
Hello! I am trying to run a PheWAS using the UKBiobank ICD10 information as phenotype input. I am slightly confused about the content of the "count" column in the PheWAS input. Does it refer to the number of individuals with the ICD10 code specified, the number of occurrences of that code per individual, or something else? Any advice would be greatly appreciated!

**Comment by RobertJCarroll** [comment]
It's specific to that individual and code. The common approach is to input dates, with the goal of getting "unique dates this individual had this phecode", but summarizing ahead of time with "distinct counts of this ICD code" can work, too. At the end of the day it's a decision that impacts performance in different ways.

**Comment by akhilpampana** [comment]
I would like to followup on this. What would be the recommended way of getting the count variable?

**Comment by RobertJCarroll** [comment]
The recommended way is to provide the date of code as the `index` value, which will compute unique phecode-days for the individual.
