### ISSUE TITLE
PheWas for cnv data

### ISSUE THREAD

**Issue by sophie-03** [PheWAS/PheWAS#67]
I am trying to carry out an association test between copy number and disease using a logistic regression model. Instead of using genotype as an input for the phewas function, could I use copy number instead? i.e. does this function just carry out a basic logistic regression test or does it involve additional steps that rely on the predictor variable being genotype information?

**Comment by RobertJCarroll** [comment]
The input is flexible, so you can input a copy number instead of an allele count. You can use `predictors` instead of `genotypes` if you wish as well. The additional steps it performs are controlled by[ this flag](https://github.com/PheWAS/PheWAS/blob/master/man/phewas_ext.Rd#L38C1-L40C4):
  \item{additive.genotypes}{
    Are additive genotypes being supplied? If so, it will attempt to calculate allele frequencies and HWE values. Default is TRUE.
  }

**Comment by sophie-03** [comment]
Hi Robert, thanks for your quick response!

No, additive genotypes are not being supplied. These are the parameters I'm currently using: 

`phewas(outcomes = phenotype,
                 predictors = copy_number,
                 covariates = covariates,
                 additive.genotypes = FALSE,
                 significance.threshold = c("p-value","bonferroni","fdr"),
                 quick.confint.level = TRUE)`

Examples of my inputs are as follows:

phenotype:
_id pheno
4997035  FALSE
4367459  FALSE
2511404  FALSE
2032922   TRUE
2769134  FALSE
1294185  FALSE_

copy_number:
_id cn1 cn2 cn3
4997035 2 2 2
4367459 2 3 2
2511404 2 2 2
2032922 2 1 2
2769134 1 2 2
1294185 1 2 4_

Is this the correct usage of the tool if I want to determine if there is an association between each cn and the phenotype?

**Comment by RobertJCarroll** [comment]
I highly recommend using `phewas_ext` instead, and merging your data ahead of time to improve clarity and options. EG:
```data = inner_join(phenotype, copy_number)
results = phewas_ext(data, phenotypes=c("pheno"), predictors = c("cn1","cn2","cn3"), additive.genotypes=FALSE)```

As long as that is how you would model the copy numbers in this situation, that's a fair approach: it will just do a logistic regression of `pheno ~ cn1` (etc). You may wish to consider covariates.
