### ISSUE TITLE
The issues of createPhenotypes

### ISSUE THREAD

**Issue by MAX-BEEN** [PheWAS/PheWAS#68]
Hello!
I have a question when I want to use function "createPhenotypes". When used the function createPhenotypes, it only showed the id in the results.

id.vocab.code.index=data.frame(id=c(101,101),vocab="ICD10",code=c("I739","R074"),index=1) 
createPhenotypes(id.vocab.code.index, min.code.count=1,  add.phecode.exclusions=T, translate=T,  vocabulary.map=PheWAS::phecode_map_icd10)

Mapping codes to phecodes...
Aggregating codes...
Mapping exclusions...
Coalescing exclusions and min.code.count as applicable...
Reshaping data...
   id
1 101
Warning messages:
1: In createPhenotypes(id.vocab.code.index, min.code.count = 1, add.phecode.exclusions = T,  :
  It is recommended to provide id.sex information to help address spurious sex-specific associations.
2: In max(!is.na(phecode$count) & phecode$count < min.code.count) :
  no non-missing arguments to max; returning -Inf
3: There was 1 warning in `summarize()`.
ℹ In argument: `count = max(count)`.
Caused by warning in `max()`:
! no non-missing arguments to max; returning -Inf 

However, when I used this code and data, it can showed me a right result.id.vocab.code.index=data.frame(id=c(101,101),vocab="ICD10",code=c("R410","R55"),index=1) createPhenotypes(id.vocab.code.index, min.code.count=1,  add.phecode.exclusions=T, translate=T,  vocabulary.map=PheWAS::phecode_map_icd10)

This really confused me, sincerely hope your answer!
Thanks!

**Comment by RobertJCarroll** [comment]
Those codes, ie, "I739" and "R074", are not ICD10 codes, so you get no results. There isn't a custom error message for this, perhaps reporting on input could be added.

If your intent was to specify "I73.9" and "R07.4", you must include the ".". While it is common practice in some settings, we rely on exact matches to the detailed code designation.

**Comment by MAX-BEEN** [comment]
Hi Robert, thanks for your quick response!
This question have been solved. 
But in this case, a new problem arised. The code in my analysis data is as described, ie, "I739" and "R074", and “M1000”. I transform these codes into the forms, which keep consistent with "PheWAS::phecode_map_icd10".  But when I search the transformed level 4  codes in the ICD-10, such as  "M10.00", "M10.01", I conuldn't find these codes in the "PheWAS::phecode_map_icd10". Should I replaced these level 4 codes by level 3 codes, ie "M10.00" to "M10.0"? If not, what should I do to slove participants with this codes?
Sincerely thanks your response again and looking forward for your answer!
Thanks!

**Comment by RobertJCarroll** [comment]
Glad that helped- at least somewhat. The description of the map I'm using can be found here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6911227/

Without digging in more, I would do what you describe and roll the codes up if they don't map. 

I would reach out to Dr. Wei-Qi Wei if you have further questions about the ICD10 maps: https://www.vumc.org/wei-lab . I took a quick look, and at least M10.00 is "newer", so perhaps that is part of it?

**Comment by MAX-BEEN** [comment]
Thank you for providing information about the  ICD-10 map you're using. I've reviewed the link you shared and gained some insight into the map in question. I found a ICD-10 Map in the UK Biobank (https://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=41270), so I consider the M10.00 is a part of M10.0.
Thank you ver much! I don't have any question!
Best wishes!
