### ISSUE TITLE
296.2 missing from ICD10 map

### ISSUE THREAD

**Issue by janneah** [PheWAS/PheWAS#71]
Hello,

I've come across a missing phecode for depression in the ICD10 map, which is in the ICD9 and CM maps. It seems there's only 296, 296.1, and 296.22 in the ICD10 map, and therefore no phecode for "Depression" or 296.2.

Best,
Janne

**Comment by RobertJCarroll** [comment]
Hi there. Two notes:
1. The more specific codes "roll up", so while there may be no direct maps, there are still codes that create cases for this phecode.
2. We do not manage the mappings in this repository; if you have concerns about the contents of the map please bring your change suggestions to Dr. Wei-Qi Wei and his team at https://www.vumc.org/wei-lab
