### ISSUE TITLE
How to get date of diagnosis of each PheCODEs

### ISSUE THREAD

**Issue by shenlan17** [PheWAS/PheWAS#73]
Hi!
I want to employ the cox regression to investigate the associations of a environmental variable with PheCODE, but i don't know how to get time. The output of _createPhenotypes_  don't contain diagnosis date,  is there other function or parameters in  PheWAS package to return it?
Thank you!

**Comment by RobertJCarroll** [comment]
The package does not support Cox regression. It’s possible you could adapt the methods to do so, but you would be on your own to develop those changes. 

You can use the code mapping tools, but you would need to summarize the patient/participant data into something suitable for cox regression. You might be able to create a suitable aggregate.fun for createPhenotypes, but I’m not sure it’d be worth the effort when it’s fairly simple to do from scratch. 

Additionally, applying cox regression would likely require some detailed design work with phewas_ext and a custom phe_as function.

**Comment by shenlan17** [comment]
Thank you for your quick reply!
I wonder if  I could map the earliest diagnosis date of ICD10 codse to correpond phecode? For example, PheCODE 008 can be mapped by 33 different ICD10 code, I firstly find the earliest diagnosis date of these 33 ICD10 code, and defined this earliest date as the diagnosis date of PheCODE 008?

**Comment by RobertJCarroll** [comment]
Yes, you could use the mapping function (`mapCodesToPhecodes` passing the ICD10 map) and then aggregate them as you describe. The analysis part is a manageable challenge, too. The infrastructure here isn't designed to what's needed for Cox Regression unfortunately.
