### ISSUE TITLE
Regarding ICD 9 phecode map in function createPhenotypes( )

### ISSUE THREAD

**Issue by Yinan-Jiang** [PheWAS/PheWAS#74]
UK biobank provided health outcome database depending on ICD9 and ICD10. When I use the function createPhenotypes, by default the parameter vocabulary.map uses [PheWAS::phecode_map](http://127.0.0.1:46187/help/library/PheWAS/help/phecode_map), which supports ICD9CM (v1.2) and ICD10CM (beta-2018). And it also includes the ICD10 beta map ([PheWAS::phecode_map_icd10](http://127.0.0.1:46187/help/library/PheWAS/help/phecode_map_icd10)). But there is no choice of ICD9 beta map in this function. How can I deal with this problem. Thanks for your kind consideration!

**Comment by Yinan-Jiang** [comment]
I have sovled this problem. Thank you.

**Comment by yangdzhong0704** [comment]
Hello, I've also encountered the same problem. Could you please share your solution approach? Or you can contact me via email: 1465890383@qq.com. I would be very grateful if you could.

**Comment by Yinan-Jiang** [comment]
> Hello, I've also encountered the same problem. Could you please share your solution approach? Or you can contact me via email: [1465890383@qq.com](mailto:1465890383@qq.com). I would be very grateful if you could.

Hello! In the function createPhenotypes, there is an argument named vocabulary.map, you can define it using ICD9 beta map by yourself. Hope this helps.
